version: '2'

networks:
  default:
    external:
      name: dev-net

services:
  nginx:
    container_name: webnode
    image: nginx
    ports:
      - 80

  mysql:
    container_name: dbnode
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
    ports:
      - 3306
